name: Release

on:
  release:
    types: [created]

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
  publish:
    needs: [validate]
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Build distributions
        run: hatch build

      - name: Publish to PyPI
        if: success()
        uses: pypa/gh-action-pypi-publish@release/v1
